name: Gary Young Photography
favicon: null
layout_spectrum: 0.99956
typography_spectrum: 0.92958
title: Boston Wedding Photographer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#272425'
    - '#615f60'
    - '#bebebe'
    - '#969696'
  brandStrength: 0.5
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
