name: Gary Young Photography
favicon: null
layout_spectrum: 0.50744
typography_spectrum: 0.17025
title: Boston Wedding Photographer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#272425'
    - '#615f60'
    - '#bebebe'
    - '#969696'
  brandStrength: 0.902593053644523
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
