name: Gary Young Photography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.31278
title: Boston Wedding Photographer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#272425'
    - '#615f60'
    - '#bebebe'
    - '#969696'
  brandStrength: 0.4375
  lightness: 0.375
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
